<?xml version="1.0" encoding="utf-8"?><Database Name="FamilyDB" Class="FamilyDataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=FamilyDB;User ID=sa" SettingsObjectName="FamilyPortal.Data.Properties.Settings" SettingsPropertyName="FamilyDBConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Consume" Member="Consume">
    <Type Name="Consume">
      <Column Name="consumeID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="amount" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="typeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="dailyID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ConsumeType" Member="ConsumeType">
    <Type Name="ConsumeType">
      <Column Name="typeID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DailyConsume" Member="DailyConsume">
    <Type Name="DailyConsume">
      <Column Name="dailyID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="amount" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ParaDetail" Member="ParaDetail">
    <Type Name="ParaDetail">
      <Column Name="detailID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="infoID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ParaInfo" Member="ParaInfo">
    <Type Name="ParaInfo">
      <Column Name="infoID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserInfo" Member="UserInfo">
    <Type Name="UserInfo">
      <Column Name="userID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="account" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="userName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="password" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.BankCard" Member="BankCard">
    <Type Name="BankCard">
      <Column Name="cardID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="cardNO" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="amount" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="dateFrom" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="dateTo" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="userID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="cardTypeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="bankID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="cityID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="isUsing" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
</Database>